version: '3.8'
services:
  nest-app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - ALLOWED_ORIGINS=http://localhost:4200
    restart: unless-stopped
    # Add health checks for better container management
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
